# Autogenerated file
def render(*a, **d):
    yield """<!doctype html>
<html>
    """
# Autogenerated file
    def render1(*a, **d):
        yield """<head>
    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">
    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>
        
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>
    
    <link href=\"/static/css/estilo.css\" rel=\"stylesheet\">
    
    
    <title>Aplicativo de medição</title>
"""
    yield from render1()
    yield """
    </head>
  
    <body>
        """
# Autogenerated file
    def render2(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
  <div class=\"container-fluid\">
    <a class=\"navbar-brand\" href=\"#\">Menu</a>
    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
      <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
      <ul class=\"navbar-nav\">
        <li class=\"nav-item\">
          <a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Inicio</a>
        </li>
        <li class=\"nav-item\">
          <a class=\"nav-link\" href=\"/configuracao/\">Configurações</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<h1 class=\"titulo\">
    Aplicativo de medição de combustivel
</h1>"""
    yield from render2()
    yield """
        
        <div class=\"tudo\">
            Configurar IP: <a href=\"/configuracao/ip\">Aqui</a></br>
            
            Configurar Wifi: <a href=\"/configuracao/wifi\">Aqui</a>
        </div>
    </body>
</html>



"""
