# Autogenerated file
def render(*a, **d):
    yield """<!doctype html>
<html>
  """
# Autogenerated file
    def render1(*a, **d):
        yield """<head>
    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">
    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>
        
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>
    
    <link href=\"/static/css/estilo.css\" rel=\"stylesheet\">
    
    
    <title>Aplicativo de medição</title>
"""
    yield from render1()
    yield """
  
      <script src=\"https://cdn.plot.ly/plotly-latest.min.js\"></script>
  </head>
  
  <body>
    """
# Autogenerated file
    def render2(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
  <div class=\"container-fluid\">
    <a class=\"navbar-brand\" href=\"#\">Menu</a>
    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
      <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
      <ul class=\"navbar-nav\">
        <li class=\"nav-item\">
          <a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Inicio</a>
        </li>
        <li class=\"nav-item\">
          <a class=\"nav-link active\" aria-current=\"page\" href=\"/fluxo\">Fluxo</a>
        </li>
        <li class=\"nav-item\">
          <a class=\"nav-link\" href=\"/configuracao/\">Configurações</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<h1 class=\"titulo\">
    Aplicativo de medição de combustivel
</h1>"""
    yield from render2()
    yield """
    
    <div class=\"tudo\">
        <h4>Status: <b id=\"status\">Online</b>!</h4>
        
        <div id=\"grafico\" style=\"width:100%; height: 500px;\"></div>
        

        <h2>Medido: <b><span id=\"litros\">"""
    yield str(d['litros'])
    yield """</span><span> Litros</span></b></h2>
        <h2>Fluxo: <b><span id=\"fluxo\">"""
    yield str(d['fluxo'])
    yield """</span><span> L/Min</span></b></h2>

        <h2>Valor: <b>R$ <span id=\"valor\">"""
    yield str(d['valor'])
    yield """</span><span></span></b></h2>
    </div>
    
    <script>
        const epoch2000=946684800;
    
        function atualiza()"""
    yield """{
            fetch('/api_historico')
                .then(response=>response.json())
                .then(dados=>"""
    yield """{
                        console.log(dados);
                
                        if(dados.status=='ok')"""
    yield """{
                            $('#status').text('Online');
                        }else"""
    yield """{
                            $('#status').text('Offline');
                        }
                
                        $('#fluxo').text(dados.fluxo_fmt);
                        $('#litros').text(dados.litros_fmt);

                        $('#valor').text(dados.valor_fmt);
                        
                        tempos_pre=dados.tempos;
                        
                        tempos_pos=tempos_pre.map(ts=>new Date((ts+epoch2000)*1000).toISOString());
                        
                        const configs=["""
    yield """{
                                x:tempos_pos,
                                y:dados.fluxos,
                                mode:'lines+markers',
                                name:'Valores',
                                line:"""
    yield """{color:'blue','width':2}
                            }];
                        
                        const layout="""
    yield """{
                                title:'Gráfico do Fluxo de Água pelo Tempo',
                                xaxis:"""
    yield """{'title':'Tempo'},
                                yaxis:"""
    yield """{'title':'Fluxo (L/Min)'}
                            };
                        
                        Plotly.newPlot('grafico',configs,layout);
                        
                        
                    })
                .catch(error=>"""
    yield """{
                        $('#status').html('Erro');
                    });
            
            setTimeout(atualiza,5000);
        };
        
        setTimeout(atualiza,5000);
    </script>
  </body>
</html>
"""
