# Autogenerated file
def render(*a, **d):
    yield """<!doctype html>
<html>
    """
# Autogenerated file
    def render1(*a, **d):
        yield """<head>
    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">
    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>
        
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>
    
    <link href=\"/static/css/estilo.css\" rel=\"stylesheet\">
    
    
    <title>Aplicativo de medição</title>
"""
    yield from render1()
    yield """
        <script src=\"/static/js/mask.ip-input.js\"></script>
        
        <script>
            $(document).ready(function()"""
    yield """{
                $('[ip-mask]').ipAddress();
            });
        </script>
    </head>
  
    <body>
        """
# Autogenerated file
    def render2(*a, **d):
        yield """<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">
  <div class=\"container-fluid\">
    <a class=\"navbar-brand\" href=\"#\">Menu</a>
    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">
      <span class=\"navbar-toggler-icon\"></span>
    </button>
    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">
      <ul class=\"navbar-nav\">
        <li class=\"nav-item\">
          <a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Inicio</a>
        </li>
        <li class=\"nav-item\">
          <a class=\"nav-link active\" aria-current=\"page\" href=\"/fluxo\">Fluxo</a>
        </li>
        <li class=\"nav-item\">
          <a class=\"nav-link\" href=\"/configuracao/\">Configurações</a>
        </li>
      </ul>
    </div>
  </div>
</nav>



<h1 class=\"titulo\">
    Aplicativo de medição de combustivel
</h1>"""
    yield from render2()
    yield """
    
        <div class=\"tudo\">
            <h3>IP atual: <b>"""
    yield str(d['ip_atual'])
    yield """</b></h3>
        
            <form method=\"POST\">
                <div class=\"form-group\">
                    <label for=\"seuip\">Seu IP</label>
                    <input name=\"ip\" ip-mask placeholder=\"000.000.000.000\" class=\"form-control\" id=\"seuip\" value=\""""
    yield str(d['configs']['ip'])
    yield """\" type=\"text\" minlength=\"7\" maxlength=\"15\" size=\"15\" pattern=\"^(?>(\d|[1-9]\d"""
    yield """{2}|1\d\d|2[0-4]\d|25[0-5])\.)"""
    yield """{3}(?1)$\" autofocus>
                </div>
              
                <div class=\"form-group\">
                    <label for=\"subrede\">Máscara de Sub-Rede</label>
                    <input name=\"subrede\" ip-mask placeholder=\"SSS.SSS.SSS.SSS\" class=\"form-control\" id=\"subrede\" value=\""""
    yield str(d['configs']['subrede'])
    yield """\" type=\"text\" minlength=\"7\" maxlength=\"15\" size=\"15\" pattern=\"^(?>(\d|[1-9]\d"""
    yield """{2}|1\d\d|2[0-4]\d|25[0-5])\.)"""
    yield """{3}(?1)$\">
                </div>
              
                <div class=\"form-group\">
                    <label for=\"gateway\">Gateway</label>
                    <input name=\"gateway\" ip-mask placeholder=\"000.000.000.000\" class=\"form-control\" value=\""""
    yield str(d['configs']['gateway'])
    yield """\" id=\"gateway\" type=\"text\" minlength=\"7\" maxlength=\"15\" size=\"15\" pattern=\"^(?>(\d|[1-9]\d"""
    yield """{2}|1\d\d|2[0-4]\d|25[0-5])\.)"""
    yield """{3}(?1)$\">
                </div>

                <div class=\"form-group\">
                    <label for=\"dns\">DNS</label>
                    <input name=\"dns\" ip-mask placeholder=\"xxx.xxx.xxx.xxx\" class=\"form-control\" id=\"dns\" value=\""""
    yield str(d['configs']['dns'])
    yield """\" type=\"text\" minlength=\"7\" maxlength=\"15\" size=\"15\" pattern=\"^(?>(\d|[1-9]\d"""
    yield """{2}|1\d\d|2[0-4]\d|25[0-5])\.)"""
    yield """{3}(?1)$\">
                </div>


                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">Enviar</button>
            </form>
        </div>
    </body>
</html>

"""
